### Using Word2Vec and Avg Word2vec
#### 1) 

In [2]:
pip install tqdm

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.1.1
[notice] To update, run: C:\Users\1000066243\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip


In [3]:
import gensim

In [4]:
from gensim.models import word2vec,keyedvectors

In [5]:
import gensim.downloader as api
word2VecApi= api.load('word2vec-google-news-300')

In [6]:
word2VecApi['king']

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [7]:
import pandas as pd

In [8]:
message =pd.read_csv("spam.csv",names=["level","message","ex1","ex2","ex3"])


In [9]:
message= message.drop(axis=0,columns= ["ex1","ex2","ex3"])

In [10]:
message

level                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will �_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [11]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\1000066243\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [12]:
from nltk.stem import WordNetLemmatizer
lemmatizer= WordNetLemmatizer()

In [13]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))

In [14]:
import re

##### Used limitizer to get the root word of the vocabulary and create a copos or paraghraph 

In [15]:
corpus=[]
for i in range(0,len(message)):
    review=re.sub('[^a-zA-z]',' ',message['message'][i])
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review ]
    review=' '.join(review)
    
    corpus.append(review)
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

### Time to work on Avg bag of word
 

In [16]:
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess 

In [17]:
word=[]
for sent in corpus:
    sentTokemn = sent_tokenize(sent)
    for token in sentTokemn:
        word.append(simple_preprocess(token))
    
word

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

Now train the model from Scrach

In [18]:
model = gensim.models.Word2Vec(word)


In [19]:
### get Vocabulary 

model.wv.index_to_key

['you',
 'to',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'be',
 'if',
 'will',
 'ur',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'ok',
 'day',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'time',
 'good',
 'then',
 'am',
 'got',
 'wa',
 'there',
 'he',
 'text',
 'only',
 'love',
 'want',
 'send',
 'txt',
 'need',
 'one',
 'today',
 'going',
 'by',
 'home',
 'don',
 'about',
 'stop',
 'she',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'our',
 'think',
 'dont',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'later',
 'they',
 'any',
 'her',
 'pls',
 'ha',
 'please',
 'co',
 'did',
 'msg',
 'been',
 'min',
 'an',
 'some',
 'dear',
 'make',
 'here',
 'night',
 'message',
 'who',
 'say',
 'well',
 're',
 'where',
 'thing',
 'much',
 'grea

#vocabulary count

model.corpus_count 

In [20]:
model.epochs ## which we choose defaule epochs 

5

In [21]:
model.wv.similar_by_word("good")

[('day', 0.9987818598747253),
 ('where', 0.9987097382545471),
 ('my', 0.9986367225646973),
 ('well', 0.9986004829406738),
 ('great', 0.9985266327857971),
 ('happy', 0.9984287619590759),
 ('hope', 0.9983877539634705),
 ('did', 0.9983425736427307),
 ('thing', 0.9982624650001526),
 ('and', 0.9982300400733948)]

In [22]:
# to get vector of out mode for any word

print(model.wv["good"])

model.wv["good"].shape

[-0.283 0.236 0.28 0.208 0.192 -0.628 0.388 0.81 -0.324 -0.202 -0.191 -0.657 -0.083 0.241 0.156 -0.188 0.0161 -0.532 -0.038 -0.692 0.281 0.372 0.312 -0.236 -0.0939 0.163 -0.332 -0.229 -0.472 0.00923 0.38 -0.0413 0.163 -0.249 -0.229 0.324 0.152 -0.264 -0.0737 -0.662 0.14 -0.181 -0.158 -0.0675 0.311 -0.0805 -0.303 -0.0452 0.175 0.275 0.0784 -0.206 -0.15 -0.0751 -0.0448 0.0857 0.213 0.0248 -0.412 0.324 0.018 -0.0189 0.174 -0.0802 -0.359 0.403 0.151 0.276 -0.35 0.36 -0.357 0.174 0.424 -0.21 0.471 0.0552 -0.104 -0.0813 -0.364 0.0745 -0.257 0.0568 -0.358 0.593 -0.19 -0.00631 0.195 0.276 0.504 0.0203 0.526 0.24 0.0699 0.183 0.647 0.451 0.236 -0.332 0.138 -0.165]


(100,)

#### For implement Avg Word2Vec we have to apply to all the sentences

In [23]:
import numpy as np

In [24]:
def AvgWord2Vec(doc):

    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)
 

In [25]:
# for tracking the progress we need library tqdm
from tqdm import tqdm

In [26]:
# apply ttqdm on every sentances and

X=[]
for i in tqdm(range(len(word))):
    X.append(AvgWord2Vec(word[i]))

  0%|          | 0/5569 [00:00<?, ?it/s]C:\Users\1000066243\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\1000066243\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5569/5569 [00:00<00:00, 7765.06it/s]


In [27]:
X

[array([-0.171, 0.187, 0.197, 0.161, 0.124, -0.441, 0.243, 0.579, -0.238, -0.119, -0.162, -0.447, -0.0457, 0.168, 0.114, -0.134, 0.00744, -0.392, -0.0186, -0.492, 0.203, 0.247, 0.226, -0.146, -0.0582, 0.132, -0.228, -0.14, -0.351, 0.0311, 0.256, -0.039, 0.0969, -0.193, -0.146, 0.239, 0.0968, -0.206, -0.0737, -0.467, 0.0853, -0.135, -0.13, -0.0361, 0.202, -0.0568, -0.192, -0.046, 0.125, 0.189, 0.0495, -0.171, -0.133, -0.0355, -0.04, 0.0422, 0.14, 0.0118, -0.323, 0.223, 0.00397, -0.0355, 0.132, -0.0582, -0.252, 0.303, 0.106, 0.201, -0.237, 0.261, -0.257, 0.127, 0.281, -0.17, 0.331, 0.0517, -0.113, -0.0453, -0.256, 0.0598, -0.184, 0.0112, -0.267, 0.383, -0.113, -0.0117, 0.104, 0.231, 0.361, 0.0285, 0.393, 0.172, 0.0384, 0.118, 0.457, 0.297, 0.172, -0.23, 0.0537, -0.131], dtype=float32),
 array([-0.157, 0.174, 0.171, 0.14, 0.108, -0.392, 0.213, 0.516, -0.211, -0.101, -0.146, -0.398, -0.0372, 0.151, 0.102, -0.128, 0.0102, -0.346, -0.0215, -0.444, 0.18, 0.212, 0.194, -0.124, -0.0498, 0.113, 

In [28]:
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))

In [29]:
len(X)  

5569

In [31]:
##independent Features
X_new=np.array(X,dtype=object)

In [32]:
X_new

array([array([-0.171, 0.187, 0.197, 0.161, 0.124, -0.441, 0.243, 0.579, -0.238, -0.119, -0.162, -0.447, -0.0457, 0.168, 0.114, -0.134, 0.00744, -0.392, -0.0186, -0.492, 0.203, 0.247, 0.226, -0.146, -0.0582, 0.132, -0.228, -0.14, -0.351, 0.0311, 0.256, -0.039, 0.0969, -0.193, -0.146, 0.239, 0.0968, -0.206, -0.0737, -0.467, 0.0853, -0.135, -0.13, -0.0361, 0.202, -0.0568, -0.192, -0.046, 0.125, 0.189, 0.0495, -0.171, -0.133, -0.0355, -0.04, 0.0422, 0.14, 0.0118, -0.323, 0.223, 0.00397, -0.0355, 0.132, -0.0582, -0.252, 0.303, 0.106, 0.201, -0.237, 0.261, -0.257, 0.127, 0.281, -0.17, 0.331, 0.0517, -0.113, -0.0453, -0.256, 0.0598, -0.184, 0.0112, -0.267, 0.383, -0.113, -0.0117, 0.104, 0.231, 0.361, 0.0285, 0.393, 0.172, 0.0384, 0.118, 0.457, 0.297, 0.172, -0.23, 0.0537, -0.131], dtype=float32), array([-0.157, 0.174, 0.171, 0.14, 0.108, -0.392, 0.213, 0.516, -0.211, -0.101, -0.146, -0.398, -0.0372, 0.151, 0.102, -0.128, 0.0102, -0.346, -0.0215, -0.444, 0.18, 0.212, 0.194, -0.124, -0.0498, 0.

In [33]:
X_new.shape

(5569,)

In [34]:
X_new[0].shape

(100,)

In [35]:
## now depedent fratur is my output feature
y = pd.get_dummies(message["level"])
y = y.iloc[:,0].values

In [36]:
y

array([ True,  True, False,  True,  True, False,  True,  True, False, False,  True, False, False,  True,  True, False,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, ...,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False, False,  True,  True,  True,  True])

In [37]:
y.shape

(5572,)

### Now We have to train the model

In [38]:
#Now we have to check the original message shape
message.shape

(5572, 2)

In [39]:
# but our coverted vector shape
X_new.shape
# so some word are missing while cheking 


(5569,)

In [40]:
# here is also ouput or dependent featue y shape 

y.shape

# what is the missing in the converted vector

(5572,)

In [41]:
 # so here you can check last 3 words is missing whihc remove while appling through regex
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus, message['message']) if i<1]

[[0, '', '645'], [0, '', ':) '], [0, '', ':-) :-)']]

In [42]:
#so in that case we have to used filtered data of output feature
## now depedent fratur is my output feature
y = message[list(map(lambda x: len(x)>0 ,corpus))]
y=pd.get_dummies(y['level'])
y=y.iloc[:,0].values

In [43]:
y.shape

(5569,)

In [44]:
## this is the final independent features
df=pd.DataFrame()
for i in tqdm(range(0,len(X))):
    df = pd.concat([pd.DataFrame(x.reshape(1, -1)) for x in X], ignore_index=True)
    

  0%|          | 0/5569 [00:00<?, ?it/s]C:\Users\1000066243\AppData\Local\Temp\ipykernel_11336\2563143580.py:4: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([pd.DataFrame(x.reshape(1, -1)) for x in X], ignore_index=True)
  7%|▋         | 389/5569 [03:32<36:49,  2.34it/s]  

In [ ]:
df.shape

NameError: name 'pd' is not defined

In [ ]:
## indipendent feature
X = df

In [ ]:
# Depedent feature Output
df["output"] =y

In [ ]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()

In [ ]:
classifier.fit(X_train,y_train)

In [ ]:
y_pred=classifier.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report

In [ ]:
score=accuracy_score(y_test,y_pred)
print(score)

In [ ]:
print(classification_report(y_test,y_pred))